# Generated by Django 3.2.8 on 2021-12-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20211220_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='post_id',
            new_name='post',
        ),
    ]
