# Generated by Django 3.2.8 on 2022-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20220323_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
